name: LambdaTest Selenium

# Trigger on push to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      # Step 3: Install dependencies (Maven)
      - name: Install dependencies
        run: mvn install

      # Step 4: Run Selenium tests on LambdaTest
      - name: Run Selenium Tests
        env:
          LT_USERNAME: ${{ secrets.althalibmohammed }}
          LT_ACCESS_KEY: ${{ secrets.LT_WTNrQpkTsTn9oHpXCrCDcOkJQCbXORI09NPlDIBSVfHSrMN }}
        run: mvn test -Dplatform="Windows 10" -Dbrowser="Chrome" -DbrowserVersion="116"
